
trigger:
- main

pool:
  vmImage: ubuntu-latest


stages:
 - stage: Build
   jobs:
    - Job: FirstJob
      steps:
      - bash: echo Build FirstJob
    - Job: SecondJob
      steps:
      - bash: echo Build SecondJob    
 - stage: DevDeploy
   Jobs:
    - Job: DevDeployJob
      steps:
      - bash: echo Build DevDeployJob
 - stage: QADeploy
   Jobs:
    - Job: QADeployJob
      steps:
      - bash: echo Build QADeployJob
 - stage: ProdDeploy
   jobs:
    - Job: ProdDeployJob
      steps:
      - bash: echo Build ProdDeployJobJob
steps:
- script: echo Job1 Step1
  displayName: 'Run a one-line script'

