trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
  - stage: Build
    Jobs:
    - Job: FirstJob
      steps:
      - bash: echo Build FirstJob
    - Job: Second Job
      steps:
      - bash: echo Build SecondJob
  - stage: DevDeploy
    Jobs:
      - Job: DevDeployJob
        steps:
        - bash: echo DevDeployJob Job
  - stage: QADeploy
    Jobs:
      - Job: QADeployJob
        steps:
        - bash: echo QADeployJob
  - stage: ProdDeploy
    Jobs:
        - Job: ProdDeployJob
          steps:
          - bash: echo ProdDeployJob

