# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

stages:
- stage: Development
  jobs:
  - job: BuildJob
    steps:
    - bash: echo "Do the build"
- stage: SIT
  jobs:
  - deployment: SITJob
    environment: SIT
    strategy:
      runOnce:
        deploy:
          steps:
          - script: echo deploy to Dev
- stage: Staging
  jobs:
    - deployment: StagingJob
      environment: Staging
      strategy:
        runOnce:
          deploy:
            steps:
            - script: echo deploy to Staging
